import "reflect-metadata";
import { Container } from "inversify";
import { registerAdminModule } from "./modules/admin.module";
import { registerAuthModule } from "./modules/auth.module";
import { registerAvailabilityModule } from "./modules/availability.module";
import { registerBookingModule } from "./modules/booking.module";
import { registerDashboardModule } from "./modules/dashboard.module";
import { registerInfrastructureModule } from "./modules/infrastructure.module";
import { registerPaymentModule } from "./modules/payment.module";
import { registerProfileModule } from "./modules/profile.module";
import { registerWalletModule } from "./modules/wallet.module";
import { registerLevelModule } from "./modules/level.module";
import { registerChatModule } from "./modules/chat.module";
import { registerReportModule } from "./modules/report.module";
import { registerReviewModule } from "./modules/review.module";
import { registerTherapistChatModule } from "./modules/therapist-chat.module";
import { registerNotificationModule } from "./modules/notification.module";
import { registerUserProgressModule } from "./modules/user-progress.module";
const appContainer = new Container();

registerInfrastructureModule(appContainer);
registerAuthModule(appContainer);
registerAdminModule(appContainer);
registerAvailabilityModule(appContainer);
registerBookingModule(appContainer);
registerPaymentModule(appContainer);
registerProfileModule(appContainer);
registerDashboardModule(appContainer);
registerWalletModule(appContainer);
registerLevelModule(appContainer);
registerChatModule(appContainer);
registerReportModule(appContainer);
registerReviewModule(appContainer);
registerTherapistChatModule(appContainer);
registerNotificationModule(appContainer);
registerUserProgressModule(appContainer);

export { appContainer };
