import "reflect-metadata";
import { Container } from "inversify";
import { registerAdminModule } from "./modules/admin.module.ts";
import { registerAuthModule } from "./modules/auth.module.ts";
import { registerAvailabilityModule } from "./modules/availability.module.ts";
import { registerBookingModule } from "./modules/booking.module.ts";
import { registerDashboardModule } from "./modules/dashboard.module.ts";
import { registerInfrastructureModule } from "./modules/infrastructure.module.ts";
import { registerPaymentModule } from "./modules/payment.module.ts";
import { registerProfileModule } from "./modules/profile.module.ts";
import { registerWalletModule } from "./modules/wallet.module.ts";
import { registerLevelModule } from "./modules/level.module.ts";
import { registerChatModule } from "./modules/chat.module.ts";
import { registerReportModule } from "./modules/report.module.ts";
import { registerReviewModule } from "./modules/review.module.ts";
import { registerTherapistChatModule } from "./modules/therapist-chat.module.ts";
import { registerNotificationModule } from "./modules/notification.module.ts";
const appContainer = new Container();

registerInfrastructureModule(appContainer);
registerAuthModule(appContainer);
registerAdminModule(appContainer);
registerAvailabilityModule(appContainer);
registerBookingModule(appContainer);
registerPaymentModule(appContainer);
registerProfileModule(appContainer);
registerDashboardModule(appContainer);
registerWalletModule(appContainer);
registerLevelModule(appContainer);
registerChatModule(appContainer);
registerReportModule(appContainer);
registerReviewModule(appContainer);
registerTherapistChatModule(appContainer);
registerNotificationModule(appContainer);

export { appContainer };
