import type { Container } from "inversify";
import { Redis } from "ioredis";
import type { IAdminRepository } from "../../../domain/repositories/admin.repository";
import type { IAvailabilityRepository, ISlotRepository } from "../../../domain/repositories/availability.repository";
import type { IBookingRepository } from "../../../domain/repositories/booking.repository";
import type { IFinanceRepository } from "../../../domain/repositories/finance.repository";
import type { IOtpCacheRepository } from "../../../domain/repositories/otp-cache.repository";
import type { IPaymentRepository } from "../../../domain/repositories/payment.repository";
import type { ISettingsRepository } from "../../../domain/repositories/settings.repository";
import type { ITherapistRepository } from "../../../domain/repositories/therapist.repository";
import type { ITherapistReviewRepository } from "../../../domain/repositories/therapist-review.repository";
import type { IUserProgressRepository } from "../../../domain/repositories/user-progress.repository";
import type { IUserJournalRepository } from "../../../domain/repositories/user-journal.repository";
import type { IUserGoalRepository } from "../../../domain/repositories/user-goal.repository";
import type { IUserRepository } from "../../../domain/repositories/user.repository";
import type { IEmailService } from "../../../application/interfaces/services/IEmailService";
import type { IGoogleService } from "../../../application/interfaces/services/IGoogleService";
import type { IOtpGenerator } from "../../../application/interfaces/services/IOtpGenerator";
import type { IPasswordHasher } from "../../../application/interfaces/services/IPasswordHasher";
import type { ITokenService } from "../../../application/interfaces/services/ITokenService";
import { TYPES } from "../../../shared/constants/tokens";
import { initRedis } from "../../databases/redis.config";
import { EmailService } from "../../external-services/email.service";
import { GoogleService } from "../../external-services/google.service";
import { OtpGenerator } from "../../external-services/otp-generator.service";
import { BcryptPasswordHasher } from "../../external-services/password-hasher.service";
import { JwtTokenService } from "../../external-services/token.service";
import { AdminRepository } from "../../repositories/admin.repository.impl";
import { AvailabilityRepository, SlotRepository } from "../../repositories/availability.repository.impl";
import { BookingRepositoryImpl } from "../../repositories/booking.repository.impl";
import { FinanceRepository } from "../../repositories/finance.repository.impl";
import { PaymentRepositoryImpl } from "../../repositories/payment.repository.impl";
import { RedisOtpCacheRepository } from "../../repositories/redis-otp-cache.repository.impl";
import { SettingsRepositoryImpl } from "../../repositories/settings.repository.impl";
import { TherapistRepository } from "../../repositories/therapist.repository.impl";
import { TherapistReviewRepository } from "../../repositories/therapist-review.repository.impl";
import { UserProgressRepository } from "../../repositories/user-progress.repository.impl";
import { UserJournalRepository } from "../../repositories/user-journal.repository.impl";
import { UserGoalRepository } from "../../repositories/user-goal.repository.impl";
import { UserRepository } from "../../repositories/user.repository.impl";
import { ILogger } from "../../../application/interfaces/services/ILoggerService";
import { Logger } from "../../external-services/logger.service";
import { SocketServer } from "../../socket/socket.server";

export const registerInfrastructureModule = (container: Container): void => {
  container.bind<Redis>(TYPES.RedisClient).toConstantValue(initRedis());

  container.bind<IAdminRepository>(TYPES.AdminRepository).to(AdminRepository).inSingletonScope();
  container.bind<IAvailabilityRepository>(TYPES.AvailabilityRepository).to(AvailabilityRepository).inSingletonScope();
  container.bind<IBookingRepository>(TYPES.BookingRepository).to(BookingRepositoryImpl).inSingletonScope();
  container.bind<IFinanceRepository>(TYPES.FinanceRepository).to(FinanceRepository).inSingletonScope();
  container.bind<IOtpCacheRepository>(TYPES.OtpCacheRepository).to(RedisOtpCacheRepository).inSingletonScope();
  container.bind<IPaymentRepository>(TYPES.PaymentRepository).to(PaymentRepositoryImpl).inSingletonScope();
  container.bind<ISettingsRepository>(TYPES.SettingsRepository).to(SettingsRepositoryImpl).inSingletonScope();
  container.bind<ISlotRepository>(TYPES.SlotRepository).to(SlotRepository).inSingletonScope();
  container.bind<ITherapistRepository>(TYPES.TherapistRepository).to(TherapistRepository).inSingletonScope();
  container.bind<ITherapistReviewRepository>(TYPES.TherapistReviewRepository).to(TherapistReviewRepository).inSingletonScope();
  container.bind<IUserProgressRepository>(TYPES.UserProgressRepository).to(UserProgressRepository).inSingletonScope();
  container.bind<IUserJournalRepository>(TYPES.UserJournalRepository).to(UserJournalRepository).inSingletonScope();
  container.bind<IUserGoalRepository>(TYPES.UserGoalRepository).to(UserGoalRepository).inSingletonScope();
  container.bind<IUserRepository>(TYPES.UserRepository).to(UserRepository).inSingletonScope();

  container.bind<IEmailService>(TYPES.EmailService).to(EmailService).inSingletonScope();
  container.bind<IGoogleService>(TYPES.GoogleService).to(GoogleService).inSingletonScope();
  container.bind<IOtpGenerator>(TYPES.OtpGenerator).to(OtpGenerator).inSingletonScope();
  container.bind<IPasswordHasher>(TYPES.PasswordHasher).to(BcryptPasswordHasher).inSingletonScope();
  container.bind<ITokenService>(TYPES.TokenService).to(JwtTokenService).inSingletonScope();
  container.bind<ILogger>(TYPES.Logger).to(Logger).inSingletonScope();
  container.bind<SocketServer>(TYPES.SocketServer).to(SocketServer).inSingletonScope();
};
