import type { Container } from "inversify";
import { Redis } from "ioredis";
import type { IAdminRepository } from "../../../domain/repositories/admin.repository.ts";
import type { IAvailabilityRepository, ISlotRepository } from "../../../domain/repositories/availability.repository.ts";
import type { IBookingRepository } from "../../../domain/repositories/booking.repository.ts";
import type { IFinanceRepository } from "../../../domain/repositories/finance.repository.ts";
import type { IOtpCacheRepository } from "../../../domain/repositories/otp-cache.repository.ts";
import type { IPaymentRepository } from "../../../domain/repositories/payment.repository.ts";
import type { ISettingsRepository } from "../../../domain/repositories/settings.repository.ts";
import type { ITherapistRepository } from "../../../domain/repositories/therapist.repository.ts";
import type { ITherapistReviewRepository } from "../../../domain/repositories/therapist-review.repository.ts";
import type { IUserProgressRepository } from "../../../domain/repositories/user-progress.repository.ts";
import type { IUserRepository } from "../../../domain/repositories/user.repository.ts";
import type { IEmailService } from "../../../application/interfaces/services/IEmailService.ts";
import type { IGoogleService } from "../../../application/interfaces/services/IGoogleService.ts";
import type { IOtpGenerator } from "../../../application/interfaces/services/IOtpGenerator.ts";
import type { IPasswordHasher } from "../../../application/interfaces/services/IPasswordHasher.ts";
import type { ITokenService } from "../../../application/interfaces/services/ITokenService.ts";
import { TYPES } from "../../../shared/constants/tokens.ts";
import { initRedis } from "../../databases/redis.config.ts";
import { EmailService } from "../../external-services/email.service.ts";
import { GoogleService } from "../../external-services/google.service.ts";
import { OtpGenerator } from "../../external-services/otp-generator.service.ts";
import { BcryptPasswordHasher } from "../../external-services/password-hasher.service.ts";
import { JwtTokenService } from "../../external-services/token.service.ts";
import { AdminRepository } from "../../repositories/admin.repository.impl.ts";
import { AvailabilityRepository, SlotRepository } from "../../repositories/availability.repository.impl.ts";
import { BookingRepositoryImpl } from "../../repositories/booking.repository.impl.ts";
import { FinanceRepository } from "../../repositories/finance.repository.impl.ts";
import { PaymentRepositoryImpl } from "../../repositories/payment.repository.impl.ts";
import { RedisOtpCacheRepository } from "../../repositories/redis-otp-cache.repository.impl.ts";
import { SettingsRepositoryImpl } from "../../repositories/settings.repository.impl.ts";
import { TherapistRepository } from "../../repositories/therapist.repository.impl.ts";
import { TherapistReviewRepository } from "../../repositories/therapist-review.repository.impl.ts";
import { UserProgressRepository } from "../../repositories/user-progress.repository.impl.ts";
import { UserRepository } from "../../repositories/user.repository.impl.ts";
import { ILogger } from "../../../application/interfaces/services/ILoggerService.ts";
import { Logger } from "../../external-services/logger.service.ts";
import { SocketServer } from "../../socket/socket.server.ts";

export const registerInfrastructureModule = (container: Container): void => {
  container.bind<Redis>(TYPES.RedisClient).toConstantValue(initRedis());

  container.bind<IAdminRepository>(TYPES.AdminRepository).to(AdminRepository).inSingletonScope();
  container.bind<IAvailabilityRepository>(TYPES.AvailabilityRepository).to(AvailabilityRepository).inSingletonScope();
  container.bind<IBookingRepository>(TYPES.BookingRepository).to(BookingRepositoryImpl).inSingletonScope();
  container.bind<IFinanceRepository>(TYPES.FinanceRepository).to(FinanceRepository).inSingletonScope();
  container.bind<IOtpCacheRepository>(TYPES.OtpCacheRepository).to(RedisOtpCacheRepository).inSingletonScope();
  container.bind<IPaymentRepository>(TYPES.PaymentRepository).to(PaymentRepositoryImpl).inSingletonScope();
  container.bind<ISettingsRepository>(TYPES.SettingsRepository).to(SettingsRepositoryImpl).inSingletonScope();
  container.bind<ISlotRepository>(TYPES.SlotRepository).to(SlotRepository).inSingletonScope();
  container.bind<ITherapistRepository>(TYPES.TherapistRepository).to(TherapistRepository).inSingletonScope();
  container.bind<ITherapistReviewRepository>(TYPES.TherapistReviewRepository).to(TherapistReviewRepository).inSingletonScope();
  container.bind<IUserProgressRepository>(TYPES.UserProgressRepository).to(UserProgressRepository).inSingletonScope();
  container.bind<IUserRepository>(TYPES.UserRepository).to(UserRepository).inSingletonScope();

  container.bind<IEmailService>(TYPES.EmailService).to(EmailService).inSingletonScope();
  container.bind<IGoogleService>(TYPES.GoogleService).to(GoogleService).inSingletonScope();
  container.bind<IOtpGenerator>(TYPES.OtpGenerator).to(OtpGenerator).inSingletonScope();
  container.bind<IPasswordHasher>(TYPES.PasswordHasher).to(BcryptPasswordHasher).inSingletonScope();
  container.bind<ITokenService>(TYPES.TokenService).to(JwtTokenService).inSingletonScope();
  container.bind<ILogger>(TYPES.Logger).to(Logger).inSingletonScope();
  container.bind<SocketServer>(TYPES.SocketServer).to(SocketServer).inSingletonScope();
};
